package Benno::Model::BennoDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Benno::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:benno',
        user => 'benno',
        password => '***REMOVED***',
        mysql_enable_utf8 => q{1},
        AutoCommit => q{1},
    }
);

=head1 NAME

Benno::Model::BennoDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Benno>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Benno::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.59

=head1 AUTHOR

Atacama Developer

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
